version: '3.9'
#  using tutorial on https://www.youtube.com/watch?v=NH4VZaP3_9s
#  as well as this blog post: https://geshan.com.np/blog/2021/12/docker-postgres/
services:
  db:
    container_name: postgres_db
    image: postgres # using image instead of build from dockerfile
    restart: always
    ports:
      - 5432:5432 #default postgres port is 5432
    environment:
      - POSTGRES_USER=${DB_USER} #pulling from environment file for variables
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres_app/setup.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80 # <local port>:<container port>
    depends_on:
      - db

  # api service will eventually go here too
  app:
    container_name: app
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - pgadmin
    restart: always

# this section goes after all the other services
volumes:
  db:
    driver: local


